### ISSUE TITLE
Doesn't work on Yosemite

### ISSUE THREAD

**Issue by rraheja** [JamshedVesuna/vim-markdown-preview#12]
Doesn't work on Yosemite since it does not match has(mac) but rather has(unix). Changing the OSNAME to mac on has(unix) makes this work but will obviously break unix support.

**Comment by JamshedVesuna** [comment]
What version of Yosemite are you on? I am on `10.10.3` and `has('mac')` returns `1` for me, which works correctly.

What does `:echo has('mac')` return for you in vim?

**Comment by rraheja** [comment]
10.10.3. I found the issue. /usr/local/bin/vim is version 7.3 which returns has('mac')=0. VimR and MacVim return 1. I updated the bundled version to 7.4 via brew and it now works as expected. May be worth mentioning in README. Closing issue.

**Comment by JamshedVesuna** [comment]
Thanks for the follow up.
