### ISSUE TITLE
Error when saving markdown file 

### ISSUE THREAD

**Issue by zarry** [JamshedVesuna/vim-markdown-preview#15]
The error I receive when saving a markdown file is below.  I installed via vundle. My [.vimrc](https://github.com/zarry/dotfiles/blob/master/vimrc.symlink)

Config specific to plugin
```
let vim_markdown_preview_browser='Google Chrome'
let vim_markdown_preview_temp_file=1
let vim_markdown_preview_toggle=2
let vim_markdown_preview_github=1
```

I am also using grip
```
% pip list | grep grip
grip (3.3.0)
```

```
Error detected while processing function Vim_Markdown_Preview_Local:
line   17:
E121: Undefined variable: b:vim_markdown_preview_github
E15: Invalid expression: b:vim_markdown_preview_github == 1
line   41:
E121: Undefined variable: b:vim_markdown_preview_temp_file
E15: Invalid expression: b:vim_markdown_preview_temp_file == 1 
```

Any help would be great!

**Comment by JamshedVesuna** [comment]
I'm having some trouble reproducing this. Can you pull the latest commits and see if the error persists?

To get more context:

1. What operating system are you using?
2. What version of vim are you on?
3. What happens if you remove all the buffer specific parts of the variables in question? For example, remove the `b:` before the variables in your error.

Thanks!

**Comment by JamshedVesuna** [comment]
Hey @zarry are you using any of the provided vim-markdown-preview options? If so, let me know.

**Comment by jmgregory** [comment]
I found this problem went away when I surrounded the equals signs with space characters

**Comment by perrygeo** [comment]
I can reproduce this error on OS X Yosemite, vim 7.4, installed in bundle for pathogen. This is out of the box behavior for me.

**Comment by michaelghinrichs** [comment]
@perrygeo having the same issue out of the box

```
Error detected while processing function Vim_Markdown_Preview:
line   17:
E121: Undefined variable: b:vim_markdown_preview_github
E15: Invalid expression: b:vim_markdown_preview_github == 1
line   40:
E121: Undefined variable: b:vim_markdown_preview_temp_file
E15: Invalid expression: b:vim_markdown_preview_temp_file == 1
```

**Comment by JamshedVesuna** [comment]
@zarry @perrygeo @michaelghinrichs Can you pull again? I changed the way variables were checked and moved everything to a global scope in 1cb74148497fa3d86b56d8202ba8fd86cce23cdd

Let me know if this error persists.

**Comment by perrygeo** [comment]
The error goes away for me. But it doesn't function properly - Ctrl-P opens a browser window at `file:///tmp/vim-markdown-preview.html` but the file is blank

**Comment by JamshedVesuna** [comment]
@perrygeo Are you using any flags (possibly `let vim_markdown_preview_temp_file=1`?) If so, check to see if the file `/tmp/vim-markdown-preview.html` actually exists. It could be that the file is being deleted before your browser opens it.

**Comment by perrygeo** [comment]
I haven't messed with any variables, just installed to ~/.vim/bundle, open md file, Ctrl-P. The file is created and still exists but is empty
```
$ ls -alth /tmp/vim-markdown-preview.html
-rw-r--r--  1 mperry  wheel     0B Nov 11 15:01 /tmp/vim-markdown-preview.html
```

**Comment by JamshedVesuna** [comment]
@perrygeo to check, do you have either `markdown` or `grip` installed as per the [requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)?

**Comment by perrygeo** [comment]
Yes, I have `grip` installed globally. In fact that's what I've been using to render markdown in lieu of a working vim plugin. 

```
$ grip
 * Running on http://localhost:6419/ (Press CTRL+C to quit)
```

**Comment by JamshedVesuna** [comment]
In order to use grip (and Github flavored markdown), put [github flag](https://github.com/JamshedVesuna/vim-markdown-preview#github) in your vimrc:

`let vim_markdown_preview_github=1`

Apologies if this was unclear from the README. Does this work?

**Comment by perrygeo** [comment]
@JamshedVesuna Yes! That was it. Can you specify that in Requirements (Options should be optional). In the case of markdown or grip as your rendering engine, it's not clear that the later choice requires additional action.

**Comment by JamshedVesuna** [comment]
Added quick documentation in b51ecf2c70d5debfda0265102edf5143876a91ec.
