### ISSUE TITLE
Doesn't work in zsh

### ISSUE THREAD

**Issue by jaypozo** [JamshedVesuna/vim-markdown-preview#18]
At first blush, this doesn't seem to work with [neovim](https://github.com/neovim/neovim). Would be great if it did. 

File does get created in `/tmp/` but is empty, resulting in blank page for preview.

OSX 10.10.5, Google Chrome, zsh shell

**Comment by JamshedVesuna** [comment]
Great to see people using neovim! Can you give me a few more details?

1. What operating system are you using?
2. What happens if you directly call the preview function? (i.e. `:call Vim_Markdown_Preview()`)
3. Are you using any other [flags/options](https://github.com/JamshedVesuna/vim-markdown-preview#options) with this plugin?
4. What are you using to compile your markdown to html? `markdown`, `grip`, other?

Thanks

**Comment by jaypozo** [comment]
1. OSX 10.10.5 with Google Chrome

2. Same thing happens. Blank page.

3. No other flags or options right now.

4. Do I need to do this? I assumed this plugin would generate that html for me, and open it in a browser. I am not currently compiling markdown to html for anything else.

**Comment by jaypozo** [comment]
Just noticed - the BundleInstall I performed added the `vim-markdown-preview` folder to `~/.vim` rather than `~/.nvim`. That would probably be related. I copied the folder over, but still no luck. I'll dig into it a bit.

**Comment by JamshedVesuna** [comment]
Check out the [OS X Requirements](https://github.com/JamshedVesuna/vim-markdown-preview#mac-os-x). You'll need to install either markdown from homebrew (or something similar) or python [grip](https://github.com/joeyespo/grip) if you want GitHub flavored markdown. These modules actually render the html, vim-markdown-preview makes this easy to do in vim.

I should probably add this to the installation section for clarity. Let me know if you have any questions about this.

**Comment by jaypozo** [comment]
It appears that a path that includes spaces causes this to break.

Haven't looked into how, but:

`/Users/Jay/Google Drive/Docs/doc.md` 
causes this plugin to break but a document at

`/Users/jay/doc.md` works just fine.

**Comment by JamshedVesuna** [comment]
Good catch! I've created a new bug: #19.

**Comment by JamshedVesuna** [comment]
@jaypozo can you pull from master and see if your problem persists? c1a6db11352d2e248c1d5c6bf6406e6c566b24a7 should fix your path space issue.

**Comment by jaypozo** [comment]
It does not fix it :disappointed:

**Comment by jaypozo** [comment]
In bash shell, in OSX, your solution would probably work. I am using zsh, which escapes spaces with `\`.

In bash: 
`/Users/jay/Google Drive`

In zsh:
`/Users/jay/Google\ Drive/`

**Comment by jaypozo** [comment]
Updated issue to include zsh.

**Comment by JamshedVesuna** [comment]
Escaping the file path with double quotes on  zsh in OS X seems to work fine for me. Can you try running the following manually and post the error back here?

`markdown "/Users/jay/Google Drive" > /tmp/test.html`

**Comment by jaypozo** [comment]
```Use of uninitialized value $text in substitution (s///) at /usr/local/bin/markdown line 245.
Use of uninitialized value $text in substitution (s///) at /usr/local/bin/markdown line 246.```

**Comment by jaypozo** [comment]
Sorry, you are totally right, this worked, in zsh:

`markdown "/Users/jay/Google Drive/Docs/spec.md"`

I assumed the zsh tab complete for dir listing was the same as what it was using for path naming.

**Comment by jaypozo** [comment]
Updated homebrew, uninstalled, reinstalled markdown. It is working now. 

Thanks for the help :grin:

**Comment by oshybystyi** [comment]
Hello! I'm sorry, but, please
can you resend me my last reply
to you?
Thanks!

2015-09-08 10:33 GMT+03:00 Jamshed Vesuna <notifications@github.com>:

**Comment by JamshedVesuna** [comment]
Hi @oshybystyi, are you referring to #11? If so, that change has already been merged into the main branch.
