### ISSUE TITLE
does not work on Ubuntu GNOME 14.04.3

### ISSUE THREAD

**Issue by uyu423** [JamshedVesuna/vim-markdown-preview#20]
ubuntu gnome 14.04.3 x86
vim 7.4.52
Grip 4.0.0
using vundle.

.vimrc
<pre>
Plugin 'JamshedVesuna/vim-markdown-preview'
let vim_markdown_preview_browser='Firefox'
let vim_markdown_preview_github=1
</pre>

Open the markdown file in vim. Control + p does not work.
but, next command well do work.
<pre>
$ grip "test.md" --export /tmp/vim-markdown-preview.html
$ see /tmp/vim-markdown-preview.html &> /dev/null &
</pre>

Why does not it work? How does it work when?

**Comment by Vincat** [comment]
Hi

This looks like an awesome plugin, if it worked. I am adding it here as I have the same system.

Ubuntu 14.04
Using Vundle

Ctrl p open the browser as expected, but it just displays a blank page.

Help, Please.

**Comment by JamshedVesuna** [comment]
@uyu423 
* Do you have xdotool and other [requirements](https://github.com/JamshedVesuna/vim-markdown-preview#unix) installed? 
* Does Firefox open at all? 
* From your post, it sounds like vim-markdown-preview is creating the file `/tmp/vim-markdown-preview.html` but not opening with [this line](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L52). What happens if you call this in vim:
```vim
call system('see /tmp/vim-markdown-preview.html &> /dev/null &')
```


@Vincat can you open a separate issue with your environment information after consulting #18?

**Comment by uyu423** [comment]
@JamshedVesuna  
Run the following command in a terminal
<pre>
 uyu423@YoWu-VM-Ubuntu > grip test.md --export /tmp/vim-markdown-preview.html
Exporting to /tmp/vim-markdown-preview.html
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
</pre>

And also run the following command in vim
<pre>
call system('see /tmp/vim-markdown-preview.html &> /dev/null &')
</pre>
Firefox window will pop up Markdown files looks good. But still controls do not work in vim + p. It merely works to the '↑' function.
The result is the same even if a different key maps

This is my .vimrc
<pre>
" vi 실행시 number line 생성
set nu
" 코딩 작업시 자동 들여쓰기
set smartindent
" 일반모드에서 / 검색시 하이라이팅
set hlsearch
" 일반모드에서 / 검색시 대소문자 구분하지 않음
set ignorecase
" Tab 관련 설정. 일반적으로 가장 많이 쓰이는 tabstop 4, shiftwidth 4
set tabstop=4
set shiftwidth=4
" 폴딩 기능 키 매핑
map <F5> v]}zf

set nocompatible
" set the runtime path to include Vundle and initialize
" NERD Tree를 왼쪽에 생성
let NERDTreeWinPos = "left"
" NERD Tree는 F2키. Tag List는 F3키에 매칭.
nmap <F2> :NERDTree<CR>
nmap <F3> :TlistToggle<CR>
" Tag list가 사용하는 ctags의 경로 설정
let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_Inc_Winwidth = 0
let Tlist_Exit_OnlyWindow = 0
let Tlist_Auto_Open = 0
" Tag list 창을 오른쪽으로 생성
let Tlist_Use_Right_Window = 1

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Vim에서 파일 탐색기를 사용할 수 있게 한다. - Nerd Tree
"Plugin 'The-NERD-tree'
Plugin 'scrooloose/nerdtree'
" Vim에서 자동완성 기능(Ctrl + P)을 키입력하지 않더라도 자동으로 나타나게 - AutoComplPop
Plugin 'AutoComplPop'
" 열려있는 소스파일의 클래스, 함수, 변수 정보 창 - Tag List
Plugin 'taglist-plus'
" Airline Plugin (http://vimawesome.com/plugin/vim-airline-sad-beautiful-tragic)
Plugin 'bling/vim-airline'
" Node JS? Jade?"
Plugin 'node.js'
Plugin 'digitaltoad/vim-jade'
Plugin 'pangloss/vim-javascript'
Plugin 'nono/jquery.vim'
" Shell Script INDENT / SYNTAX Plugin
Plugin 'sh.vim'
Plugin 'bsh.vim'
" PHP Plugin (http://vimawesome.com/?q=tag:php)
Plugin 'StanAngeloff/php.vim'
Plugin '2072/PHP-Indenting-for-VIm'
Plugin 'shawncplus/phpcomplete.vim'
" Auto Syntax Checker (http://vimawesome.com/plugin/syntastic)
Plugin 'scrooloose/syntastic'
" for jQuery
Plugin 'jQuery'
" for Markdown Preview
Plugin 'JamshedVesuna/vim-markdown-preview'

" Molokai Color scheme
"Plugin 'molokai'
"Plugin 'lsdr/monokai'

" All of your Plugins must be added before the following line
call vundle#end()            " required

" Makdown Plugin Github Preview 설
let vim_markdown_preview_browser='/usr/bin/firefox'
let vim_markdown_preview_github=1
" Airline 설정
let g:airline#extensions#tabline#enabled = 1
"let g:airline#extensions#tabline#left_sep = ' '
"let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_powerline_fonts = 1

" Syntastic 설정
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" set javascript syntax chacker for syntastic
"let g:syntastic_javascript_checkers = ['jshint']

" vim-jade plugin의 Jade Syntax Highlighting을 위한 옵션. 이상하게 이게 없으면 하이라이팅이 작동하지 않는다.
au BufNewFile,BufReadPost *.jade set filetype=jade

" apply molokai color scheme
"let g:molokai_original = 1
let g:rehash256 = 1

" apply colorschemes
set t_Co=256
syntax on
colorscheme molokai
" colorscheme desert
" colorscheme slate

filetype on
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
</pre>

**Comment by Vincat** [comment]
Hi

Thanks this has been fixed.

**Comment by JamshedVesuna** [comment]
@uyu423 have you resolved this issue? I will close this issue soon.

**Comment by uyu423** [comment]
@JamshedVesuna sorry. i dont using this plugin now. and i cant resolved problem.
