### ISSUE TITLE
page empty

### ISSUE THREAD

**Issue by xavierartot** [JamshedVesuna/vim-markdown-preview#22]
Hi,
when I start the previous my file is empty no source code?
Thank you

**Comment by JamshedVesuna** [comment]
Do you correctly have the [requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements) installed? This can be caused by not having a markdown rendering program available, such as `markdown` or `grip`.

Can you provide more information about your system, flags / options used?

**Comment by mooreniemi** [comment]
i thought i had markdown on my system but turns out i didnt, and saw this symptom too. was easily solved on mac with `brew install markdown`
