### ISSUE TITLE
No see command in my distribution

### ISSUE THREAD

**Issue by perrin4869** [JamshedVesuna/vim-markdown-preview#23]
I'm trying to use this plugin in Slackware. I have `xdotool` installed and all, but the markdown never shows up in the browser. Is there any way to support distributions which do not have `see` in them? How about using `xdg-open` instead, since that is something most distros have?

**Comment by JamshedVesuna** [comment]
Added `xdg-open` support via 956b15428acbf93687e9e1f464b7a2c7ed4e4a03.

**Comment by JamshedVesuna** [comment]
Be sure to set this flag in your .vimrc:

`let vim_markdown_preview_use_xdg_open=1`
