### ISSUE TITLE
Previewing temporary files, without .md extension, how?

### ISSUE THREAD

**Issue by rmaddox** [JamshedVesuna/vim-markdown-preview#25]
I am editing markdown files from a database, and for such, temporary files are created, without .md extension.

Is there a way, that I get the preview without having .md or other markdown extension?

**Comment by JamshedVesuna** [comment]
Definitely! As the function `Vim_Markdown_Preview` is loaded with this plugin, you can simply type the following to preview *any* file in markdown:

`:call Vim_Markdown_Preview()`

You can also make a keyboard shortcut for this as so:

`nnoremap <C-p> :call Vim_Markdown_Preview()<Cr>`

Which maps Control-p.

**Comment by rmaddox** [comment]
I have changed my database editing to spill out .md temporary files, rather that then to change your plugin. 
I am wondering if there would be easy way to put a template and show it in template... I guess I will make it somehow. Thank you much, this is helping me greatly.

**Comment by JamshedVesuna** [comment]
As I've shown above, you can even render files without the `.md` extension as a markdown preview.

Could you elaborate on what you mean by "put a template and show it" ?

**Comment by rmaddox** [comment]
While Markdown is often used for HTML generation, I was thinking, there could be an automatic way, to put  a template in a directory, and within template to put something like {$markdown} where the generated HTML content would appear inside.

**Comment by JamshedVesuna** [comment]
Can you elaborate? What do you mean by "put a template in a directory" ?

**Comment by rmaddox** [comment]
Markdown is used for HTML generation. It would be nice, that user of this plugin, may simply copy his own HTML template and put it in some of plugin templates, or configure the HTML template for the preview.

For example: template would be named like template.html
```
<html>
{$markdown_body}
</html>
```
of course, such template would have its own CSS, style, and markups. User of the plugin would be able to actually see how the page looks like on the website, by pressing CTRL-P

**Comment by JamshedVesuna** [comment]
Can't you just source the markdown file that's being created, or even use an iframe? This seems cool, but outside the scope of this specific plugin. Feel free to fork!

**Comment by rmaddox** [comment]
I am now simply using macro in .vimrc
https://gist.github.com/rmaddox/8ad4c414fcfc70214c62
