### ISSUE TITLE
Does not display Swedish Characters, Unicode issue?

### ISSUE THREAD

**Issue by eleijonmarck** [JamshedVesuna/vim-markdown-preview#26]
Hey,

I cannot display swedish characters with using this plugin. It renders
![image](https://cloud.githubusercontent.com/assets/7727602/12172224/e9596138-b54f-11e5-9d16-d600c4e5ebb6.png)

**Comment by eleijonmarck** [comment]
Love the plugin though!!

**Comment by JamshedVesuna** [comment]
As a temporary workaround, can you try using [`grip`](https://github.com/JamshedVesuna/vim-markdown-preview#github) to render the html file?

**Comment by JamshedVesuna** [comment]
@eleijonmarck have you resolved this by using `grip`?

**Comment by beli3ver** [comment]
Yes. Grip fixed it.
I have the same issue with German special Chars.
So use grip and it will fix it.
Maybe you write it in the README so everyone with special chars know it.

**Comment by JamshedVesuna** [comment]
Noted in 55632163fa3e4e016a90a6385df75d1328678a21
