### ISSUE TITLE
Opens a new tab on every buffer write [OSX / NeoVim / Chrome]

### ISSUE THREAD

**Issue by chapati23** [JamshedVesuna/vim-markdown-preview#28]
Plugin works great, only thing is that it opens a new tab on every write instead of reloading the existing one

**Comment by JamshedVesuna** [comment]
Can you provide more details about your environment?

- What OS are you on?
- What browser are you using?
- What vim_markdown_preview options are you using?

**Comment by chapati23** [comment]
sure:
- OSX 10.11.3
- Chrome 47.0.2526.106 (64-bit)
- Vim Config:
```
let vim_markdown_preview_toggle=2
let vim_markdown_preview_hotkey='<C-m>'
let vim_markdown_preview_temp_file = 1
```

**Comment by JamshedVesuna** [comment]
Interestingly, the `open` util on OS X only refreshes Safari tabs. I believe OS X + Google Chrome would require an AppleScript. It would be great to include this!

Thanks for finding this :smile:

**Comment by JamshedVesuna** [comment]
I have a diff coming soon to fix this.

**Comment by JamshedVesuna** [comment]
@chapati23 c56e91916c06705d73b62e337d8fa8a625633054 should fix this issue. Let me know if you have any problems!

**Comment by chapati23** [comment]
fixed it! thank you!
