### ISSUE TITLE
OS X opens Chrome even when Safari is default

### ISSUE THREAD

**Issue by mjedmonds** [JamshedVesuna/vim-markdown-preview#33]
Hi,

Google Chrome is opened despite the default preview setting, and the resulting html file is only loaded in displayed in Safari.

It makes sure chrome is running, if chrome is already running, nothing happens, if chrome is not running, it is launched, which is unwanted behavior.

**Comment by JamshedVesuna** [comment]
Thank you for catching that! It was wiped by a previous commit. I've included a fix in 5838d1d45091ecb18ea51fa51c66d9dc91a3ebb8.

Also, be sure to have your default browser set to Safari. The intent here was to set the default browser of this plugin to that of a fresh install of OS X.
