### ISSUE TITLE
Documentation update/Problem with .md files

### ISSUE THREAD

**Issue by OliPelz** [JamshedVesuna/vim-markdown-preview#35]
Had a problem with this wonderful plugin. 
The ```Ctrl-p``` hotkey only worked on ```.markdown``` and ```README.md``` files but never on any other ```.md``` file e.g. ```readme.md```. 
After looking around I found out that the only valid ```.md``` file is ```README.md``` according to Vim's  ```filetypes.vim```, see [here](http://superuser.com/questions/701496/no-syntax-highlight-on-md-files).
Maybe you could update your documentation to tell users about it because it really gave me headaches why hotkey wasn't working for me: 

"By default, when in a ```.markdown``` or ```.md``` file, and ```Ctrl-p``` is pressed, this plugin will either open a preview in your browser, or refresh your current preview (can be remapped, see Options). ..."

**Comment by JamshedVesuna** [comment]
Good observation! I found that setting the `filetype` in my `.vimrc` solves this issue:
```vim
au BufNewFile,BufRead *.md set filetype=markdown
```

**Comment by OliPelz** [comment]
yes! works like a charm, thank you!
