### ISSUE TITLE
has no effect, vim-markdown-preview.html is zero bytes

### ISSUE THREAD

**Issue by rainccrun** [JamshedVesuna/vim-markdown-preview#42]
Browser is blank, has no effect, vim-markdown-preview.html is zero bytes

Enviroment:
OS: MacOS X Yosemite 10.10.5
vim: macvim 7.4.1831

I hava tried both chrome and safari browser, both no effect.

Thanks.

**Comment by JamshedVesuna** [comment]
This sounds like an issue with either `markdown` or `grip`. Are you using any of the optional flags? Can you confirm that `markdown` or `grip` is installed?

**Comment by rainccrun** [comment]
I've installed plasticboy/vim-markdown for syntax highlight, and have no idea with grip....

**Comment by JamshedVesuna** [comment]
Please view this module's [Requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements). You'll need to install a small module that renders markdown files to HTML. Let me know if you have any questions or issues regarding this process.

**Comment by rainccrun** [comment]
It works! 
Thanks! It's my fault...
