### ISSUE TITLE
Consider remove huge images from plugin repository.

### ISSUE THREAD

**Issue by hoxnox** [JamshedVesuna/vim-markdown-preview#43]
Your plugin is huge because of images in the repository. It is the biggest plugin in my vim installation (it's more than 10 times bigger then [CtrlP](https://github.com/kien/ctrlp.vim) with 450 commits). It's not small as you write in your README.
Consider remove images. And you should clean somehow .git directory after that.

**Comment by JamshedVesuna** [comment]
This is a very good point. Keeping this plugin as light as possible is essential. For now, I've moved the main header gif to Imgur and removed the larger gif entirely. Will decide to add it back in later if necessary.

Closed by 907dda0d3c29bf8d31f923093e9df420f828d33a
