### ISSUE TITLE
It doesn't update content in browser automatically 

### ISSUE THREAD

**Issue by rupc** [JamshedVesuna/vim-markdown-preview#45]
I'm using Google Chrome, and all option is set on default. I only can see it when I press ctrl + p.
How can I fix it?

**Comment by JamshedVesuna** [comment]
As noted in the [Usage](https://github.com/JamshedVesuna/vim-markdown-preview#usage), this plugin is built for manual updating, through the use of a hot-key or buffer write, making it extremely light and minimal. If you'd like to have your preview update live while you type in your vim buffer, I suggest looking at a polling engine plugin such as [vim-instant-markdown](https://github.com/suan/vim-instant-markdown)
