### ISSUE TITLE
Ctrl-P Opens Tab, but vim-markdown-preview.html is blank (0 Bytes)

### ISSUE THREAD

**Issue by BertArnie** [JamshedVesuna/vim-markdown-preview#47]
file:///tmp/vim-markdown-preview.html opens but shows nothing. Any ideas?

OS is Mac OS X.

Also, what is meant by Markdown is a requirement? What is the proper way to install Markdown.pl? Does the system path have to have the alias markdown=Markdown.pl?

Maybe I am doing something wrong and can add to the README once I figure out what.

**Comment by jgberg** [comment]
yup... same fail for me too

**Comment by BertArnie** [comment]
https://github.com/JamshedVesuna/vim-markdown-preview/pull/48
It works on OS X by changing the command call "markdown" to "Markdown.pl".

**Comment by JamshedVesuna** [comment]
This is a common issue (see previously closed issues). Do you have the proper[ requirements installed](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)? @BertArnie it looks like you're using a different way to render markdown. I'm more than happy to accept a PR to support it!

**Comment by samspot** [comment]
Same for me, though since I didn't want to install markdown, i tried the grip installation.  grip works fine but ctrl-p does not.  I do have the .vimrc line from the readme.

**Comment by PauloASilva** [comment]
@BertArnie I did install perl `Text::Markdown` module using `cpanm`. As a workaround you can create a symbolic link `markdown -> Markdown.pl`

**Comment by JamshedVesuna** [comment]
`Markdown.pl` should now be supported with 2cee512ddca87818f0ec34246c9c794877cd9001 by setting:
```vim
let vim_markdown_preview_perl=1
```
Note that the options still need to be refactored, causing `vim_markdown_preview_github` to override the `vim_markdown_preview_perl` options.
