### ISSUE TITLE
On install, Ctrl+P hangs MacVIM until open is run in Terminal

### ISSUE THREAD

**Issue by craiga** [JamshedVesuna/vim-markdown-preview#50]
After installing this plugin, I found that MacVIM would hang whenever I pressed Ctrl+P until I manually ran `open -g /tmp/vim-markdown-preview.html`, at which point it started working.

**Comment by JamshedVesuna** [comment]
Are you using any of the [optional flags](https://github.com/JamshedVesuna/vim-markdown-preview#options)? What browser are you using?
If you're able to manually open `/tmp/vim-markdown-preview.html`, sounds like it might be an osascript issue with Google Chrome.

**Comment by craiga** [comment]
I haven't configured any of the options, so I'm expecting it to open with Safari (which is what the README says it should do).

**Comment by JamshedVesuna** [comment]
By default, this [plugin does](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L87) what you manually ran: `open -g /tmp/vim-markdown-preview.html`. What version of macvim are you using? What version of macOS are you using?

**Comment by craiga** [comment]
macOS 10.12.1, MacVIM 8.0 (116).

I've taken a look through the `.vim` file and I can't really make heads of tails of what might've caused this issue (I'm just trying switching from Textmate to MacVIM at the moment), but I find it odd that there's no mention of Safari in this file.

**Comment by JamshedVesuna** [comment]
By default, `open` will use your default system browser. On macOS, this is Safari (unless otherwise changed). On the command-line, can you run through the following steps:
```sh
markdown README.md > /tmp/vim-markdown-preview.html
open -g /tmp/vim-markdown-preview.html
```
Does this work?

**Comment by Phosphor303** [comment]
I confirm the issue for OS X 10.11.6, MacVim 8.0 (120).

As `markdown` is not installed by default, I installed it via `brew` to test your suggested steps with an empty markdown file. The second step opened the markdown preview file in Safari, but it was empty and did not refresh when writing stuff in the markdown file.

**Comment by JamshedVesuna** [comment]
@Phosphor303 if `markdown README.md > /tmp/vim-markdown-preview.html` renders an empty html file can you try using [another markdown to html generator](http://daringfireball.net/projects/markdown/)? You can also try using [grip](https://github.com/joeyespo/grip).

**Comment by JamshedVesuna** [comment]
Closing this out for now, feel free to re-open if this is still an issue.
