### ISSUE TITLE
/tmp/vim-markdown-preview.html was empty

### ISSUE THREAD

**Issue by ginsonwang** [JamshedVesuna/vim-markdown-preview#51]
I'm sorry, my english was terrible, i hope you will understand what i saying
i have done all things what the README wants me to do, but when i press ctrl-p , the page was empty
![image](https://cloud.githubusercontent.com/assets/22736704/21535767/b3f2f314-cdb4-11e6-91ea-bef240ef3d75.png)

i use lubuntu 16.04 and chromium

**Comment by JamshedVesuna** [comment]
Do you have the [necessary requirements](https://github.com/JamshedVesuna/vim-markdown-preview#unix) for Ubuntu installed? If so, are you using any [custom options](https://github.com/JamshedVesuna/vim-markdown-preview#options)?

**Comment by ginsonwang** [comment]
@JamshedVesuna 
I'm sorry, I forgot to install the Markdown, when i try it, the vim-markdown-preview works
thank you very much
