### ISSUE TITLE
browser shows a blank html

### ISSUE THREAD

**Issue by mendezmariano** [JamshedVesuna/vim-markdown-preview#52]
No preview is shown on the browser. It get focus but a white html is shown.

**Comment by JamshedVesuna** [comment]
Have you installed the [necessary requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)? What happens if you run the command manually? Either `markdown README.md > out.html`? or `grip README.md --export out.html`?

**Comment by mendezmariano** [comment]
sorry it was my fault, grip was incorrectlly installed!! 
Thank you
