### ISSUE TITLE
Vim_Markdown_Preview() doesn't run preview in Google Chrome

### ISSUE THREAD

**Issue by minademian** [JamshedVesuna/vim-markdown-preview#54]
I have read through the docs, but the plugin won't load the preview in Google Chrome.

My setup:

- Google Chrome `Version 56.0.2924.87 (64-bit)`
- Vim 8.0.71
- Mac OS X El Capitan 10.11.6
- `zsh`
- Vundle
- remapped to `<C-m>`

**Comment by Skarlso** [comment]
Same settings here, with latest version + vundle, with the slight difference that I set Chrome as the opening Browser.

**Comment by JamshedVesuna** [comment]
I'm having some trouble reproducing the issue. Have you installed the [necessary requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)? What happens if you run the command manually? 
Either `markdown README.md > out.html`? or `grip README.md --export out.html`? Is there contents in `out.html`?

**Comment by minademian** [comment]
Yeah, I've installed the necessary requirements. Running the command manually works and then I can open the output file in Google Chrome. But, when I try to run it from inside vim, it doesn't work at all. It works as expected in Safari.

**Comment by JamshedVesuna** [comment]
Do you have the [`vim_markdown_preview_browser` option](https://github.com/JamshedVesuna/vim-markdown-preview#browser) set? For example:

`let vim_markdown_preview_browser='Google Chrome'`

**Comment by minademian** [comment]
Alright. I think I figured it out. I was reloading my changes to `.vimrc` with `:so %`. I tried exiting Vim and reloading the file with `source`. Now, it works as expected. I'm confused because I thought the two commands are identical! :)

**Comment by JamshedVesuna** [comment]
No worries 😄 closing this out for now. Feel free to reopen if you have any issues
