### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by roytseng-tw** [JamshedVesuna/vim-markdown-preview#55]
Here's my situation.
I'm on windows using MobaXterm to connect remote Ubuntu 16.04 server.
MobaXterm forward browser window to my computer with X11 forwarding .
The first press of <ctrl + p> functions normally.
However, whenever I press <ctrl + p> again trying to refresh the content, new tab opened and shows this 
![image](https://cloud.githubusercontent.com/assets/5027936/24325400/203125b6-11d3-11e7-9d13-b0730d06a578.png)

Can this be fixed?
Thank for your help.

**Comment by roytseng-tw** [comment]
Currently, I figure out to use grip directly.

**Comment by JamshedVesuna** [comment]
This seems to be outside the scope of this plugin - closing out for now. Feel free to reopen if you find a specific issue. Right now, VMP wouldn't cause an Internal Server Error to the best of my knowledge.
