### ISSUE TITLE
Press Ctrl+P, I got blank page on Chrome

### ISSUE THREAD

**Issue by vincentsmh** [JamshedVesuna/vim-markdown-preview#57]
Hi,

When I press Ctrl+P, I get a blank screen on my chrome. I also check the file /tmp/vim-markdown-preview.html and it is empty.

My OS is Ubuntu 16.10.

**Comment by JamshedVesuna** [comment]
Have you installed the [necessary requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)? What happens if you run the command manually? Either `markdown README.md > out.html`? or `grip README.md --export out.html`?

**Comment by vincentsmh** [comment]
Hi,

I installed your mentioned requirements, then everything if fine now. Thanks.
