### ISSUE TITLE
Blank page on Mac OS X Sierra

### ISSUE THREAD

**Issue by boompig** [JamshedVesuna/vim-markdown-preview#59]
Tested with `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  6 2016 12:07:41)` as well as `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  9 2017 06:42:38)`. Tested with Safari and Chrome. None of these configurations works for me.

Contents of the temp file `/tmp/vim-markdown-preview.html` are empty for me.

**Comment by JamshedVesuna** [comment]
Have you installed the [necessary requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements)? What happens if you run the command manually? Either `markdown README.md > out.html`? or `grip README.md --export out.html`?

**Comment by boompig** [comment]
Realized this problem was caused by working inside a virtualenv by accident where these two packages were not installed. Thanks for the help.
