### ISSUE TITLE
File Renders; Chromium Doesn't Open File

### ISSUE THREAD

**Issue by fanuch** [JamshedVesuna/vim-markdown-preview#60]
OS: `Arch Linux`
Browser: `Chromium`
Editor: `NeoVIM`

I'm glad I found your plug in, it's an excellent idea!
Installed fine on `NeoVim` and installed `Markdown` and `xdotool` using `pacman` package manager.

I checked the `/tmp/` dir and I can see the rendered file there but it doesn't open Chromium. 
Are there any other debugging techniques I can use to find out what is going on?

**Comment by JamshedVesuna** [comment]
We have not yet added Chromium support, but it would be awesome to have! 
You can see the commands that this plugin runs [here](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L77-L92). I'd be happy to accept a Chromium PR!

**Comment by JamshedVesuna** [comment]
Closing this out for now, I'd be happy to accept a Chromium integration PR 😄
