### ISSUE TITLE
Pandoc support

### ISSUE THREAD

**Issue by twsh** [JamshedVesuna/vim-markdown-preview#61]
This is nice.

[Pandoc](http://pandoc.org/) support would be useful to some people, I think. I've tried to add it here: https://github.com/twsh/vim-markdown-preview/commit/261d88f3081b17f7c23e6244088b0c58d1bbe24d

Would you be interested in a pull request?

**Comment by JamshedVesuna** [comment]
That would be great, thank you! Be sure to add it to the [local function](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L116) as well.

**Comment by twsh** [comment]
OK, I have done that and made a PR: https://github.com/JamshedVesuna/vim-markdown-preview/pull/62
