### ISSUE TITLE
pandoc preview can't show equation

### ISSUE THREAD

**Issue by jhjungCode** [JamshedVesuna/vim-markdown-preview#66]
There is no convert option for converter equation.

so, I suggest to add  "--mathjax" option

elseif g:vim_markdown_preview_pandoc == 1
    call system('pandoc --smart --standalone --mathjax"' . b:curr_file . '" > /tmp/vim-markdown-preview.html')

**Comment by JamshedVesuna** [comment]
I'd be happy to accept a PR that adds the mathjax flag, possibly through another [VMP option](https://github.com/JamshedVesuna/vim-markdown-preview#options). Ultimately, I'd like to refactor these options into something simpler.

**Comment by JamshedVesuna** [comment]
Closing this out for now. Feel free to re-open with a PR
