### ISSUE TITLE
can this plugin use in windows？

### ISSUE THREAD

**Issue by itgoyo** [JamshedVesuna/vim-markdown-preview#67]
Requirements just for Mac or Unix,Can i be used on windows?

**Comment by JamshedVesuna** [comment]
As of now, VMP doesn't support auto reloading the browser based markdown preview. I've had an [open issue](https://github.com/JamshedVesuna/vim-markdown-preview/issues/6) to add Windows support for a while but haven't gotten around to it. Happy to get a PR though!
