### ISSUE TITLE
Pressing CTRL+P does nothing

### ISSUE THREAD

**Issue by refaelsh** [JamshedVesuna/vim-markdown-preview#71]
Hi,

Pressing CTRL+P does nothing. I followed the install instructions to the letter. I use Arch Linux.

Thanks.

**Comment by refaelsh** [comment]
It was my mistake. Sorry. Vundle was misconfigured.

**Comment by dmalt** [comment]
Hi!

Same thing for me.
vim-markdown-preview.html is rendered in /tmp directory after Ctrl + p but chrome doesn't open. 
I also use arch linux.

**Comment by CathrineTeng** [comment]
@dmalt , I have this issue too. Have you figured it out? My os is fedaro

**Comment by dmalt** [comment]
@CathrineTeng, nope. I stopped using markdown preview after all.

**Comment by kinh-nguyen** [comment]
> @dmalt , I have this issue too. Have you figured it out? My os is fedaro

@CathrineTeng I need to exit and reload the file again (after `brew install markdown` on  Mac)
