### ISSUE TITLE
Hitting request limit to github

### ISSUE THREAD

**Issue by nickwilmes** [JamshedVesuna/vim-markdown-preview#72]
I seem to be enjoying this tool too much. 😄 

In the error message they state that you can provide grip with your username and password to increase the request limit.  It would be awesome if the preview plugin could somehow provide this option.  My first thought would be to set them in the .vimrc, but putting a plaintext password in there may not be the most secure option.

![screen shot of issue](https://user-images.githubusercontent.com/2826469/30984538-73a34ae2-a442-11e7-9b45-695ed3885aa2.png)

**Comment by JamshedVesuna** [comment]
If you have a GitHub account, you should be able to setup authentication with your ssh keys: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/.

Feel free to reopen if you're unable to do this 😄
