### ISSUE TITLE
Markdown and Pandoc?

### ISSUE THREAD

**Issue by RichardDooling** [JamshedVesuna/vim-markdown-preview#76]
I use pandoc for everything. I don't have original Markdown installed anywhere. If I'm telling vim-markdown-preview to use pandoc, why is it still telling me to check the requirements? Must I also install John Gruber's ancient Markdown somewhere? 

Thanks

Rick

**Comment by JamshedVesuna** [comment]
You should be able to use pandoc by setting [this option](https://github.com/JamshedVesuna/vim-markdown-preview#the-vim_markdown_preview_pandoc-option). Feel free to re-open if this doesn't work.
