### ISSUE TITLE
Support image loading

### ISSUE THREAD

**Issue by edbrannin** [JamshedVesuna/vim-markdown-preview#8]
When I preview a Markdown document with images, they don't load.

It would be nice if the webapp had a catch-all route that checked for files relative to the markdown-being-previewed.

**Comment by JamshedVesuna** [comment]
Duplicated as #7.

**Comment by JamshedVesuna** [comment]
@edbrannin I added a new function `Vim_Markdown_Preview_Local()` that supports image loading by rendering the html file locally (in the current directory).  Simply uncomment [line 104](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L104) and comment out [line 100](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L100) to preserve the Ctrl-p mapping.

Let me know if this fixes the image loading problem.

**Comment by JamshedVesuna** [comment]
@edbrannin closing this out. Feel free to reopen if you have further questions or concerns.
