### ISSUE TITLE
How to Install Daring Fireball's Markdown.pl?

### ISSUE THREAD

**Issue by yohannes** [JamshedVesuna/vim-markdown-preview#98]
This is probably a dumb question. I have scoured through past issues and even did some ddg-ing but I cound't find the answer on where should I put the markdown.pl file. Can anyone point me in the right direction?

**Comment by lcvisser** [comment]
Anywhere on your `$PATH` should be fine. It's invoked as `markdown`, so rename it.

**Comment by yohannes** [comment]
@lcvisser thanks for the pointer. it works now.
